INSERT INTO participants(name, document, email, mobile, city, country, occupation, university, career, type, status, created, created_by)
VALUES 
('MARIANA DE JESUS DAVILA FUENTES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHOEL CALANI LORENA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CINTHIA LAYME FAJARDO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CARLOS RICARDO RUIZ SEGOVIA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FRANZ RONALD SORIA COLQUE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARCELO LOPEZ PLAZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GONZALO ADOLFO LUGO CASANOVA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('WEIMAR ALARCON REYNAGA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE MIGUEL CANAVIRI MARTINEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MANUEL ENRIQUE BARRENECHEA FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GUSTAVO MARTINEZ ROLLANO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('BEKER GUTIERREZ MURILLO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('BACILIO VELASQUEZ FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('DEYANIRA LINARES ORTIZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN CARLOS VARGAS FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('SERGIO JAVIER CRUZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('RODOLFO MARTIN PEÑARANDA ZAMORA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('EDWARD CRISTOBAL DIAZ VALDA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE DAVID KANCHI DURAN','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ARIEL ANGEL SANTILLAN REYNA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FERNANDO ROMERO HERRERA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE RODRIGO AGREDA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GUSTAVO ELVIS HUANQUIRI QUISPE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN TELLEZ PAREDES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('RAUL CARMELO VILLCA SAIGUA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LUZMILA JHANETH CARLOS ACUÑA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ADRIANA VANESSA UZEDA RODRIGUEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('DIANA NICOLE SERRUDO ORTIZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('RENSO DAVID JEREZ AUCACHI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LIZETH ERLINDA PEREZ CALDERON','','',0,'','','','USFX', '', 'S','A',now(), 1),
('WILSON ALEJANRO LAZCANO PALMA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ADHEMAR JHONNY***************','','',0,'','','','USFX', '', 'S','A',now(), 1),
('NESTOR FRANKLIN CASTILLO CENTURIO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CLAUDIA MIREYA SANCHEZ ZAMBRANA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GISSEL ALEXANDRA LEON SALAZAR','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LESLY RAYNE JURADO LOPEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MAURICIO PARI COLODRO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARIBEL SERRUDO LOPEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('SAMUEL JORGE REYES MONTAÑO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE ELIAS FRANCO IBARRA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CAROL GRACIA MIXTO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FANNY KAREN FLORES MURILLO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('YOSELI CONDORI ROMERO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('PABLO DANIEL NOYA QUIROZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN SERGIO PITA COLQUE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('INES GONZALES CAYARA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GONZALO CARLO AYAVIRI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LESLY RAQUEL FLORES TORABLA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FELIX ALEJANDRO ZELAYA ORELLANA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MAYRA VALERIA TORRICOS SENZANO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('EDSON HUARAYO POLARES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('WILSON POLARES ORTIZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('BANESSA CAIHUARA SANTOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('HENRY PEÑARANDA CORONADO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('EDUARDO FLORES VACA GUZMAN','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARIA ANGELICA MIRANDA MENDOZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('DANIEL ALEJANDRO GUTIERREZ MONTAÑO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN JOSE PEREZ YUCRA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ARIEL ACHU GABRIEL','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOEL TITO MAMANI CHAVARRIA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('KEVIN EDWIN ZANGA CAERO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FAUSTINO OCHOA GONZALES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LUIS ALFONSO RAMIREZ GARCIA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('THOMAS CARMONA CALVIMONTES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOEL ALEJANDRO RIOS VARGAS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CELINA QUISPE FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE LUIS MENACHO MAMANI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('VLADIMIR TORREZ ALBA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CARLA FERNANDA ANIBARRO MUÑOZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ALEX JOHN HURTADO FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE GUADALUPE CALIZAYA MAMANI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('EDWARD CAMARGO MARCA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LIZANDRO MAMANI RAMOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ERICK MANZANO MUÑOZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('WILSON ALFONZO MEDINA CHIPANA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('DANIELA NICOLE NINA SAAVEDRA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ERIK NEUMAN GALLARDO CASTILLO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FRANZ WILSON AVILA FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FERNANDO SAMUEL HILARIO QUISPE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHON CARLOS DIAZ SOLIZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN SERGIO VILLAFAN CANIZARES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN JESUS HUANQUIRI QUISPE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('RIGOBERTO MIRANDA ZUÑIGA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('SANTIAGO CAMPUZANO VILLARROEL','','',0,'','','','USFX', '', 'S','A',now(), 1),
('NICOLAS SEBASTIAN CASTRO SOLIZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('SERGIO JHONATAN CORTEZ HERRERA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ARIEL PACHECO ALEJANDRO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ALEXANDER VARGAS RIVERA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN MANUEL SANTOS MENDOZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CARLOS MARCELO TORRES VARGAS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LUIS GUSTAVO ORTIZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARITZA APALA PACO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CARLOS ARIEL ONTIVEROS SUBELZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ALEYDA BELEN PACHECO HERRERA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('DANIEL INTI ALBERTO CHOQUE MAMANI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('PAOLA ANDREA CABRERA FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('BRYAN FERNANDEZ FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ERICK ROJAS ESCUDERO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARCELO CALVIMONTES ACUÑA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE GABRIEL POQUECHOQUE ESPADA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JORGE CARLOS ALBERTO TERCEROS BARRON','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ERICK AMERICO GUZMAN RIOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARCO ANTONIO TICONA RIOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHONNY RAMIREZ UMACACHO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ERWIN MARIO LEON RAMOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('DIEGO GONZALO ESCALANTE ANTEZANA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('SOLEDAD TERESA NINA HUANCA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARCELO RODRIGO DURAN MAMANI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MIGUEL ANGEL ACEITUNO AVALOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ENRIQUE BALDERRAMA RIVERA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('SBIETH ANAHI ARANDIA ANDRE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GABRIELA POMACUSI QUICHU','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ERVIN REINALDO CALDERON RODRIGUEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARIO EDSON PIMENTEL ROMERO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GUIDO TORIHUANO BARRANCOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ORLANDO DELGADO CHOQUE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('NELSON FLORES OROPEZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ABRIL ALEJANDRA FUENTES ANDIA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('AXEL GIANFRANCO LOAYZA CRUZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ABETT LEVY HILARION JULURI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CRISTIAN ORLANDO FLORES RODRIGUEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSELINE GABRIELA DIAZ JIMENEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GABRIELA MICHELE QUINTANILLA ANTEQUERA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN MARCO TOLA SANCHEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('DANIEL QUISPE RICALDE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('WILLANS MISAEL ROMERO CONDORI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHONNY AGUSTIN ZUÑIGA MENDEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ADA MAGDIEL CAZON PEREZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LELIS DURAN GOMEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('PAOLA LISSETTE MONTECINOS AMEZAGA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN ANTONIO RODRIGUEZ PRUDENCIO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSSELINE ALEJANDRA MIRANDA LAURA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CRISTHIAN WALTER CALCINA CHOQUE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARIBEL VEDIA PERKA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN CARLOS MAMANI QUEQUE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ADRIAN MAMANI CAZAS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHAMYL EDGAR ALIZARES RIVAS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CRISTIAN MANUEL SOLIS GUERRA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('OMAR NUÑEZ DEL PRADO FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JESUS PAREDES TOMAS NICASIO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ILSEN ROMERO CARABALLO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ELIZABETH VILLARPANDO VALENCIA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ERWING CHOQUERIVE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ISAAC JOSE LUIS RAMIREZ CHOQUE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARCELO HUMBERTO MURILLO TORRICO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MAYERLIN ORTIZ ESPADA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FRANKLIN CORREA PACO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CARLOS FRANCISCO ANDRADE FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('NORMA MOSTACEDO PARRA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARIO DANIEL DELGADO BALZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ANA VALERIA JANCO LAUREAN','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ANABEL RODRIGUEZ PEREZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('IVAN ALFREDO CRUZ TRUJILLO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GERSON GUTIERREZ MURILLO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JESUS SALINAS MANCILLA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('PILAR LETICIA CALLAHUARA RIOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('BRISA PAMELA BAPTISTA RODRIUEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LISBETH FERNANDEZ MURUCHI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GIOVANA MARCIA IBAÑEZ MENDOZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHENNY IVANA MIRANDA VALVERDE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE AMILCAR ARANCIBIA SOTO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARCOS GUSTAVO SAAVEDRA DIAZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LUIS DANIEL SALAMANCA BARRAL','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN JOSE PINTO TORRES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ROSA BARBARA MAMANI LUGO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ELMER ARROYO COLQUE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ANGELA GONZALES VENTURA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('DANIEL WILLY PATZI HUMERES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN CARLOS GARRADO ZARATE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('WENDY ALIZON DURAN RENGIFO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MAGALY POSIABO CHAMO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('HEIDY TINUCO MONTES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MICHAEL WILDER SALINAS MONTOYA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JASMINA JAEL HUALLPA OYOLA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('EDGAR MOLLO FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JORGE JAVIER ROMAN LLANOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('RODRIGO DANUBIO MOREIRA SOTO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('WALDO VILLANUEVA GONZALES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CORNELIA MAMANI MARCANI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FRANZ REYNALDO LOPEZ SANDOVAL','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ALBERTO ORLANDO PAREDES MAMANI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARLENE YUCRA SEÑA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CARLOS FABRICIO DAVILA LAURA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CARLOS OLIVER ARAMAYO MAMANI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('VICTOR MANUEL OPORTO BETANZOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CRISTIAN GUSTAVO MARTINEZ FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('EDWIN CALLE PEREZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GUSTAVO CHAVARRIA HERRERA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('RAUL TELLEZ MERLOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JULIO CESAR ARANCIBIA MIRANDA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ROGER LAURA CACERES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARIO ANARATA DIAZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('SEBASTIAN LOAYZA DAZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ELIAS ORTEGA GUEVARA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN CARLOS MALDONADO MAMANI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('EDWIN TICONA LIMA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ANA MARIA POZO FERRUFINO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARIO JONATAN TORRES BARRERA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('DAVID MAX TITO ANDRE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('YAQUELIN PEREZ CEREZO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FELIPE FLORES FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FAUSTA SARA FLORES VARGAS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('NOELIA ALEXANDRA CALDERON CHAVEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHONNY CHOQUE CRUZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MAIDY ROCIO MAMANI LUGO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FREDDY MANUEL SALVADOR RUIZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ALEX JUVENAL CRUZ FERNANDEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHOANA BARRIENTOS DORADO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('HAIDE SENZANO RIBERA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE MAURICIO BAZAGOITIA AYLLON','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHON ERICK RAMIREZ LEAÑOS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JAVIER CAMPOS MORENO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('WILSOR TITO HUANCA COLQUE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('BRYAN DAVID ERAZO CHOQUE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LINO FERNANDO VILLCA JAITA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('OSCAR ALFREDO NAVARRO CORS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('IGOR SANTIAGO NAVARRO BALANZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('RODRIGO JAIRO LOAYZA CORONADO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN FLORES SURA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('PEDRO LUIS ACHO ZARATE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ALVARO LUIS ZAPATA MOSCOSO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHONATTAN IBARRA CONDO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CRISTIAN UÑO MANRIQUE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN IGNACIO RASGUIDO HIGUERAS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('HEIDY RIOSSETH PACO CRUZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('BRENDA KELY MITA MARTINEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('WILBERT PINTO CHAMBI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ROMAN GERMAN ARANCIBIA RAMIREZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('KEVIN JHONATAN ARENAS LOPEZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LESLIE ALEJANDRA ROSSO ROMERO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GILARY VALERIA GUMIEL CARRASCO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ARCIL VASQUEZ CARBALLO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MIKEL ALVAREZ BEJARANO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ANGELA BELEN RODRIGUEZ SOLIZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('LIGIA NATALY DIAZ VALDA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('GABY ELIANA RAMIREZ ESPINOZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN CARLOS AMADOR YUCRA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('EDZON MOISES CAYO MOLLO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('DIEGO NAVARRO CORS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ALVARO JOAQUIN NAVARRO CORS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CINTHIA CABA ALDANA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHOELY MARTINEZ CRUZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('AMERICO ITAMAR ECHALAR GUZMAN','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FRANCISCA SOLEDAD SERAPIO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('IVAN FAJARDO SULLCA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('HUGO ROBERTO GUTIERREZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ALCIRA CAZAS GARECA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FERNANDO TALAVERA MAMANI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ENRIQUE MONTES BAUTISTA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JUAN DANIEL MONTERO POCLABE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE ARTURO LA FUENTE FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('HECTOR ALEJANDRO GUTIERREZ MAZALA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARIOLY CECILIA CONTRERAS CONDORI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('EDGAR CRISTOPHER POZO SALINAS','','',0,'','','','USFX', '', 'S','A',now(), 1),
('YAMIL CRISTHIAN FERNANDEZ ARAMAYO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('WILSON WIDER MENDOZA COPA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ISRAEL ERNESTO ACEITUNO ROMERO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ERIK RODRIGO MAMANI ESPINOZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CARLOS ROBERTO AYAVIRI PALLARES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('AYLIN POLA OROPEZA ACOSTA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE DAID MANZANO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('FRAYA JHEMINA CHAMBI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ALEXANDER CHOQUE POLO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOEL ORLANDO MAMANI MURIÑO','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CLIVER SOLEDAD COLQUE IQUISE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('HIDELBERTO CAYO QUISPE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('CRISTIAN EDUARDO BONIFAZ HEREDIA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARIANELA SARAVIA ORTEGA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MIGUEL MAURICIO ORTIZ QUISPE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JOSE IGNACIO DURAN DAZA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('ELIANA VELIZ HUARACHI','','',0,'','','','USFX', '', 'S','A',now(), 1),
('DANIELA LIZONDO CHOQUE','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JHAQUELIN ANAGUA MUÑOZ','','',0,'','','','USFX', '', 'S','A',now(), 1),
('JORGE ANDRES COPA ARANCIBIA','','',0,'','','','USFX', '', 'S','A',now(), 1),
('MARIA ELENA RAMOS FLORES','','',0,'','','','USFX', '', 'S','A',now(), 1),
('XELIER MARIN CHOQUE','','',0,'','','','','','E','I',now(),1),
('JIMENA RUTH CASTELLON MANSILLA','','',0,'','','','','','P','A',now(),1),
('GENARO MAURICIO ALVAREZ ORIAS','','',0,'','','','','','E','A',now(),1),
('NATALIA OVIEDO ACOSTA','','',0,'','','','','','E','A',now(),1),
('EDDY ESCALANTE USTARIZ','','',0,'','','','','','E','A',now(),1),
('HERALD CHOQUE VARGAS','','',0,'','','','','','E','A',now(),1),
('MIGUEL ANGEL BORDA GUTIERREZ','','',0,'','','','','','E','A',now(),1),
('ISABEL LIGIA ESCOBAR MIRANDA','','',0,'','','','','','P','A',now(),1),
('BRIAN JAVIER VARGAS GUTIERREZ','','',0,'','','','','','E','A',now(),1),
('ALEJANDRA XIMENA TOLA PACHECO','','',0,'','','','','','E','A',now(),1),
('DANIEL EDUARDO CARVALLO MOLINA','','',0,'','','','','','P','A',now(),1),
('ALVARO ARIEL MARTINEZ MANCILLA','','',0,'','','','','','E','A',now(),1),
('LUIS YERKO LAURA TOLA','','',0,'','','','','','E','A',now(),1),
('ERICK ARTURO QUISPE AREVILCA','','',0,'','','','','','E','A',now(),1),
('MIGUEL ANGEL BULUCUA VINACHA','','',0,'','','','','','P','A',now(),1),
('JESUS ALEXANDER LLANOS LLANOS','','',0,'','','','','','E','A',now(),1),
('AYRTON NIGEL ALBORTA FLORES','','',0,'','','','','','P','A',now(),1),
('JAQUELINE VARGAS CAZAS','','',0,'','','','','','E','A',now(),1),
('ALEJANDRO LOMA SALDIAS','','',0,'','','','','','E','A',now(),1),
('ERICK MOISES ARTEAGA VACA','','',0,'','','','','','E','A',now(),1),
('KATHERINE VALVERDE LEIGUE','','',0,'','','','','','E','A',now(),1),
('JOSE MENDOZA VARGAS','','',0,'','','','','','P','A',now(),1),
('LICET VEDIA COPA','','',0,'','','','','','E','A',now(),1),
('MARCO EMILIO CALLISAYA ALEJO','','',0,'','','','','','E','A',now(),1),
('MARIBEL CHOQUE RENGEL','','',0,'','','','','','P','A',now(),1),
('VALERIA GARRON ALMENDRAS','','',0,'','','','','','E','A',now(),1),
('MARLENE CHOQUE RENGEL','','',0,'','','','','','P','A',now(),1),
('XELIER MARIN CHOQUE','','',0,'','','','','','E','I',now(),1),
('JIMENA RUTH CASTELLON MANSILLA','','',0,'','','','','','P','A',now(),1),
('GENARO MAURICIO ALVAREZ ORIAS','','',0,'','','','','','E','A',now(),1),
('NATALIA OVIEDO ACOSTA','','',0,'','','','','','E','A',now(),1),
('EDDY ESCALANTE USTARIZ','','',0,'','','','','','E','A',now(),1),
('HERALD CHOQUE VARGAS','','',0,'','','','','','E','A',now(),1),
('MIGUEL ANGEL BORDA GUTIERREZ','','',0,'','','','','','E','A',now(),1),
('ISABEL LIGIA ESCOBAR MIRANDA','','',0,'','','','','','P','A',now(),1),
('BRIAN JAVIER VARGAS GUTIERREZ','','',0,'','','','','','E','A',now(),1),
('ALEJANDRA XIMENA TOLA PACHECO','','',0,'','','','','','E','A',now(),1),
('DANIEL EDUARDO CARVALLO MOLINA','','',0,'','','','','','P','A',now(),1),
('ALVARO ARIEL MARTINEZ MANCILLA','','',0,'','','','','','E','A',now(),1),
('LUIS YERKO LAURA TOLA','','',0,'','','','','','E','A',now(),1),
('ERICK ARTURO QUISPE AREVILCA','','',0,'','','','','','E','A',now(),1),
('MIGUEL ANGEL BULUCUA VINACHA','','',0,'','','','','','P','A',now(),1),
('JESUS ALEXANDER LLANOS LLANOS','','',0,'','','','','','E','A',now(),1),
('AYRTON NIGEL ALBORTA FLORES','','',0,'','','','','','P','A',now(),1),
('JAQUELINE VARGAS CAZAS','','',0,'','','','','','E','A',now(),1),
('ALEJANDRO LOMA SALDIAS','','',0,'','','','','','E','A',now(),1),
('ERICK MOISES ARTEAGA VACA','','',0,'','','','','','E','A',now(),1),
('KATHERINE VALVERDE LEIGUE','','',0,'','','','','','E','A',now(),1),
('JOSE MENDOZA VARGAS','','',0,'','','','','','P','A',now(),1),
('LICET VEDIA COPA','','',0,'','','','','','E','A',now(),1),
('MARCO EMILIO CALLISAYA ALEJO','','',0,'','','','','','E','A',now(),1),
('MARIBEL CHOQUE RENGEL','','',0,'','','','','','P','A',now(),1),
('VALERIA GARRON ALMENDRAS','','',0,'','','','','','E','A',now(),1),
('MARLENE CHOQUE RENGEL','','',0,'','','','','','P','A',now(),1),
('ALENNY MARLYE ZARATE ROCHA','','',0,'','','','','','P','A',now(),1),
('ISAIAS MOROCHI SANCA','','',0,'','','','','','E','A',now(),1),
('SERGIO FRANCO RAMIREZ VASQUEZ','','',0,'','','','','','E','A',now(),1),
('FABIOLA CLAROS FUENTES','','',0,'','','','','','E','A',now(),1),
('MARIA ANGELICA CEREZO VELASQUEZ','','',0,'','','','','','P','A',now(),1),
('VIVIAN AMPARO HERRERA ADUVIRI','','',0,'','','','','','P','A',now(),1),
('JOEL ERWIN VELIZ FLORES','','',0,'','','','','','E','A',now(),1),
('RUBEN JOSUE SANDOVAL BRAVO','','',0,'','','','','','E','A',now(),1),
('JOSE DIDA MAMANI GOMEZ','','',0,'','','','','','E','A',now(),1),
('KEVIN JUNNIOR PINO MITA','','',0,'','','','','','E','A',now(),1),
('BENJAMIN JIMMY ROMANO CAREAGA','','',0,'','','','','','E','A',now(),1),
('REIDEN FLORES PEREZ','','',0,'','','','','','E','A',now(),1),
('LIZETH DANIELA QUISPE LOPEZ','','',0,'','','','','','E','A',now(),1),
('DRACEN KEVIN ROMERO RIVERO','','',0,'','','','','','E','A',now(),1),
('EDWIN DEYMAR MIRANDA MARTINEZ','','',0,'','','','','','E','A',now(),1),
('SHAKIRA THALIA ROMAY COSSIO','','',0,'','','','','','E','A',now(),1),
('ARIEL ERWIN CEJAS PATRICIO','','',0,'','','','','','E','A',now(),1),
('ALEXANDRA ANZE VEDIA','','',0,'','','','','','E','A',now(),1),
('CRISTINA PATRICIA TORRES CAMPUZANO','','',0,'','','','','','P','A',now(),1),
('JOSE GABRIEL SANGA','','',0,'','','','','','E','A',now(),1),
('JASSIN BENJAMIN GOMEZ FORONDA','','',0,'','','','','','E','A',now(),1),
('JOSE LUIS MAMANI REYES','','',0,'','','','','','E','A',now(),1),
('ISAIAS SALAS MONTESINOS','','',0,'','','','','','E','A',now(),1),
('BERNABÉ QUIÑONES FLORES','','',0,'','','','','','E','A',now(),1),
('JOSE LUIS LESCANO OZUNA','','',0,'','','','','','E','A',now(),1),
('MARIA NORMA SACACA JANCKO','','',0,'','','','','','E','A',now(),1),
('BRISA MARIVEL VILACAHUA VELIZ','','',0,'','','','','','P','A',now(),1),
('OSCAR ANTONIO SANCHEZ MANCILLA','','',0,'','','','','','E','A',now(),1),
('KEVIN HAROL TALAVERA CASTRO','','',0,'','','','','','E','A',now(),1),
('NAPOLEON SALUSTIANO CHOQUE SOLANO','','',0,'','','','','','E','A',now(),1),
('FABRICIO LIZONDO PERALES','','',0,'','','','','','E','A',now(),1),
('MARYSABEL FLORES MENDEZ','','',0,'','','','','','E','A',now(),1),
('MARIO EZEQUIEL SANCHEZ COPA','','',0,'','','','','','E','A',now(),1),
('RUBEN GERMAN MAMANI MENDEZ','','',0,'','','','','','E','A',now(),1),
('ANAHI YANDIRA ALAVIA BRAVO','','',0,'','','','','','E','A',now(),1),
('CARLOS FERNANDO BARRANCOS PEREZ','','',0,'','','','','','E','A',now(),1),
('KATERINNE ARANCIBIA VEIZAGA','','',0,'','','','','','P','A',now(),1),
('BRENDA TAMARA CORONEL RIVERA','','',0,'','','','','','E','A',now(),1),
('ROMINA JHORGELLY MENDOZA SAAVEDRA','','',0,'','','','','','E','I',now(),1),
('LILIANA HUANCA COLQUE','','',0,'','','','','','E','I',now(),1),
('BLUMBERG AYRTON CLAROS TEJERINA','','',0,'','','','','','E','A',now(),1),
('ROSSIBEL ALEJANDRA CASTRO CRUZ','8520728','',0,'','','','UATF','INGENIERIA DE SISTEMAS','E','A',now(),1),
('Alberto Benitez Ponce','','',0,'','','ING. DE SISTEMAS','','','P','A',now(),1),
('Alberto Benitez Reynoso','','',0,'','','ING. CIVIL','','','P','A',now(),1),
('Miguel Ángel Ruiz Sagredo','10663116','',60278301,'','','','USFX','Ingenieria de Sistemas','O','A',now(),1),
('Vania Eunice Calvimontes Muñoz','7515719','',74426809,'','','','USFX','Ingenieria de Sistemas','O','A',now(),1),
('Mita Gumiel Haen Mauricio','10349698','',74406482,'','','','USFX','Ingenieria de Sistemas','O','A',now(),1),
('Reynaga Familia Heber Gonzalo','8564978','',79737904,'','','','USFX','Ingenieria de Sistemas','O','A',now(),1),
('Ckuno Torihuano Jhonny Rodrigo','10849269','',71154436,'','','','USFX','Ingenieria de Sistemas','O','A',now(),1),
('Cristian Henrry Bobarin Ala','4011382','',78689550,'','','','USFX','Ingenieria de Sistemas','O','A',now(),1),
('Cesar Sarzuri Gutierrez','10377197','',67653557,'','','','USFX','Ingenieria de Sistemas','O','A',now(),1),
('Rosado Mamani Harold','4110898','',72861897,'','','','USFX','Ingenieria de Sistemas','O','A',now(),1),
('Romero Gutierrez Lidia Maribel','8626300','',67163130,'','','','USFX','Ingenieria de Sistemas','O','A',now(),1),
('Huanaco Familia Gustavo','12612027','',68636773,'','','','USFX','Ingenieria de Sistemas','O','A',now(),1),
('NOHELIA MENDOZA VASQUEZ','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('ALISON PAOLA JANCKO FUENTES','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('MARIA FERNANDA YAÑEZ MOSCOSO','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('FRANZ RAMIRO LOPEZ PECHO','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('SHANON NICOLE MOGRO CASTILLO','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('NATALIA RICELY PORTUGUEZ OCHOA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('KHRISTIAN SALINAS PADILLA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JOSE ENRIQUE IGLESIAS','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('CARLOS VLADIMIR ROCHA RIVERA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JOSE LUIS BARRÓN MUÑOZ','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('DAVID VARGAS LASTRA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JAVIER ANDRES TAVERA SANDOVAL','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('FLOR ENRIQUEZ ANDRES','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('DIEGO ARMANDO PARRAGA ORTUSTE','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('ENRIQUE OCTAVIO MARTINEZ INOCHEA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JANETH AYLIN TORRES MOSTACEDO','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('MAGALY DORIS CONDORI CANAZA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JHONNY FREDDY FLORES FLORES','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('ELVIS GORENA ROSADO','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('ADRIAN BALDIVIEZO COLQUE','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('MIGUEL MARCELO DAZA ZUNA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JUAN MILTON MAMANI VASQUEZ','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('ISRAEL MEDRANO CASILLAS','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JHANETH CHOCLLU ROMERO','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('WILMA JHUNIER RODRIGUEZ VIDAURRE','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('CARLOS XAVIER ROMERO SANDY','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('ALVARO SEBASTIAN CEPEDA CHOQUE','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JAIME DELGADO MELCHOR','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('MARY MICHELLE SUBIETA MOYA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('LUIS FERNANDO NUMA NAVARO ARIAS','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JOSE MIGUEL CHOQUE COLQUE','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JANETHDEL ROSARIO PACHECO CAMARGO','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('BARBARA LOZA ZABALA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('MARTIN ANDRES DAVEZIES POVEDA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('MARIANA JHOSELIN APAZA MAMANI','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JHISELA LLANQUE MOLLO','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('LUIS ALBERTO CAYHUARA CHOQUEPALPA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('MONSERRAT JESSICA ALFARO CHUGA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('ALEJANDRO REYES MENDOZA','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('KARLITA SEVILLA CHAVEZ','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('NAARA DAYANA CEREZO CONDORI','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1),
('JUAN BENITO LEON SANCHEZ','','',0,'SUCRE','BOLIVIA','','','','S','A',now(),1);

